# Generated by Django 4.2.5 on 2023-09-14 01:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gunshot',
            old_name='baretta_model_92_gun',
            new_name='ak_12_gun',
        ),
        migrations.RenameField(
            model_name='gunshot',
            old_name='colt_m4_carbine_gun',
            new_name='ak_47_gun',
        ),
        migrations.RenameField(
            model_name='gunshot',
            old_name='glock_19_gun',
            new_name='imi_desert_eagle_gun',
        ),
        migrations.RenameField(
            model_name='gunshot',
            old_name='ruger_lc9_gun',
            new_name='m16_gun',
        ),
        migrations.RenameField(
            model_name='gunshot',
            old_name='smith_and_wesson_and_p_9_gun',
            new_name='m249_gun',
        ),
        migrations.AddField(
            model_name='gunshot',
            name='m4_gun',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='mg_42_gun',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='mp5_gun',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='zastava_m92_gun',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
