# Generated by Django 4.2.5 on 2023-09-19 23:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0004_alter_gunshot_imi_desert_eagle_gun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunShotDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location', models.CharField(max_length=200)),
                ('parish', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='gunshot',
            old_name='ak_12_gun',
            new_name='ak12_gun',
        ),
        migrations.RemoveField(
            model_name='gunshot',
            name='ak_47_gun',
        ),
        migrations.RemoveField(
            model_name='gunshot',
            name='location',
        ),
        migrations.RemoveField(
            model_name='gunshot',
            name='m16_gun',
        ),
        migrations.RemoveField(
            model_name='gunshot',
            name='m249_gun',
        ),
        migrations.RemoveField(
            model_name='gunshot',
            name='mg_42_gun',
        ),
        migrations.RemoveField(
            model_name='gunshot',
            name='mp5_gun',
        ),
        migrations.RemoveField(
            model_name='gunshot',
            name='zastava_m92_gun',
        ),
        migrations.AddField(
            model_name='gunshot',
            name='prob',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gunshot',
            name='gun_detector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detector.gunshotdetector', verbose_name='Gun Shut Detector'),
        ),
    ]
