# Generated by Django 4.2.5 on 2023-09-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0005_gunshotdetector_rename_ak_12_gun_gunshot_ak12_gun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunshotdetector',
            name='latitude',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
        migrations.AlterField(
            model_name='gunshotdetector',
            name='longitude',
            field=models.DecimalField(decimal_places=17, max_digits=20),
        ),
    ]
